name: Continuous Integration

on:
  push:
    branches:
      - '**'
    tags:
      - '*'

jobs:
  build:
    name: Build
    runs-on: windows-2019
    outputs:
      version: ${{ steps.semver.outputs.version }}
      should-release: ${{ steps.semver.outputs.should-release }}
      is-prerelease: ${{ steps.semver.outputs.is-github-prerelease }}
    steps:
      - id: semver
        name: Checkout
        uses: EasyDesk/action-semver-checkout@v1
      - name: Build
        uses: EasyDesk/action-dotnet-build@v1
        with:
          warnings-as-errors: true
      - name: Publish
        uses: EasyDesk/action-dotnet-publish@v1
        with:
          output-dir: publish
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: build-artifacts
          path: publish
  release:
    name: GitHub release
    runs-on: ubuntu-20.04
    needs: [build]
    if: needs.build.outputs.should-release == 'true'
    concurrency: release
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: build-artifacts
      - name: Zip Build Assets
        run: zip -r asssets ./*
      - name: Release
        uses: EasyDesk/action-semver-release@v1
        with:
          version: ${{ needs.build.outputs.version }}
          prerelease: ${{ needs.build.outputs.is-prerelease }}
          files: |
            assets.zip